name: Deploy Frontend

on:
  push:
    branches: [ main ]
    paths:
      - 'frontend/**'
      - '.github/workflows/main_datasoko-web.yml'
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set working directory
        run: cd frontend

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install deps
        run: |
          cd frontend
          npm install

      - name: Build
        run: |
          cd frontend
          npm run build

      - name: Prepare deployment package
        run: |
          mkdir deploy
          cp -r frontend/.next deploy/
          cp -r frontend/public deploy/
          cp frontend/package.json deploy/
          cp frontend/package-lock.json deploy/

      - name: Deploy to Azure
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'datasoko-web'
          publish-profile: ${{ secrets.AZURE_FRONTEND_WEBAPP_PUBLISH_PROFILE }}
          package: deploy
